language: python
python:
        - '3.6'

before_script:
        - pip install -r requirements.txt

services:
        - postgresql

env: DJANGO_SETTINGS_MODULE=chasa.settings.travis

script:
        - ./manage.py test
